name: Test

on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/setup-python@v4
      - run: python -c "import os; path = os.path.expanduser('~/Desktop'); print(os.path.exists(path))"
      - run: python -c "import os; print(os.path.exists('~/Desktop'))"
      - run: python -c "import os; newpath = os.path.expanduser('~/Desktop/newdir'); print(os.path.exists(newpath))"
